# Simple workflow for deploying static content to GitHub Pages
name: Set metadata to allowed

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      target-video:
        description: Video ID of the target video
        required: true
      additional-data:
        description: Extra data provided by speaker


# Allow pull request
permissions:
  pull-requests: write
  repository-projects: write
  contents: write

jobs:
  conversion:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update metadata (with additional data)
        if: github.event.inputs.additional-data !=''
        run: python ./tools/metadata_setup.py ${{ github.event.inputs.target-video }} null null null true false ${{ github.event.inputs.additional-data }}
      - name: Update metadata (without additional data)
        if: github.event.inputs.additional-data ==''
        run: python ./tools/metadata_setup.py ${{ github.event.inputs.target-video }} null null null true false null
      - name: Add metadata to be tracked
        run: |
          git add static/src/subtitle/${{ github.event.inputs.target-video }}.srt.meta
      - name: Create Pull Request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: "Added allowance for ${{ github.event.inputs.target-video }}"
            title: "Added allowance for ${{ github.event.inputs.target-video }}"
            body: "Added allowance for ${{ github.event.inputs.target-video }}"
            base: main
            labels: automated-pr
            branch: allowance-${{ github.event.inputs.target-video }}
            delete-branch: true