# Simple workflow for deploying static content to GitHub Pages
name: Add reviewed metadata

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      target-video:
        description: Video ID of the target video
        required: true
      target-language:
        description: The language
        required: true
        default: en
        type: choice
        options:
          - en
          - zh_tw
          - ja
      reviewer:
        description: The person who reviewed the subtitle
        required: true


# Allow pull request
permissions:
  pull-requests: write
  repository-projects: write
  contents: write

jobs:
  conversion:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update metadata
        run: python ./tools/metadata_setup.py ${{ github.event.inputs.target-video }} ${{ github.event.inputs.target-language }} "${{ github.event.inputs.reviewer }}" null null null
      - name: Add metadata to be tracked (en)
        run: |
          git add static/src/subtitle/${{ github.event.inputs.target-video }}.srt.meta
      - name: Create Pull Request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: "Added reviewer for ${{ github.event.inputs.target-video }}.${{ github.event.inputs.target-language }}"
            title: "Added reviewer for ${{ github.event.inputs.target-video }}.${{ github.event.inputs.target-language }}"
            body: "Added reviewer for ${{ github.event.inputs.target-video }}.${{ github.event.inputs.target-language }}"
            base: main
            labels: automated-pr
            branch: reviewer-${{ github.event.inputs.target-video }}-${{ github.event.inputs.target-language }}
            delete-branch: true