name: Update SRT file index

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      target-video:
        description: Video ID of the target video
        required: true
      target-language:
        description: The language to be updated
        required: true
        default: en
        type: choice
        options:
          - en
          - zh_tw
          - ja


# Allow pull request
permissions:
  pull-requests: write
  repository-projects: write
  contents: write

jobs:
  conversion:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.3
      - name: Checkout
        uses: actions/checkout@v3
        # Converts specified subtitle to transcript
      - name: Update SRT file index
        run: python ./tools/update_srt_index.py ${{ github.event.inputs.target-video }} ${{ github.event.inputs.target-language }}
      - name: Create Pull Request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: "Updated index for ${{ github.event.inputs.target-video }}.${{ github.event.inputs.target-language }}"
            title: "Updated index for ${{ github.event.inputs.target-video }}.${{ github.event.inputs.target-language }}"
            body: "Updated index for ${{ github.event.inputs.target-video }}.${{ github.event.inputs.target-language }}"
            base: main
            labels: automated-pr
            branch: update-srt-${{ github.event.inputs.target-video }}-${{ github.event.inputs.target-language }}
            delete-branch: true